"""
Django settings for mychruutundruebli project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ps5p7zke5c+f3$*p=wxyu$-p941tsr0p@e+jj#=a#^r+l+t5*!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'juntagrico',
    'impersonate',
]

AUTHENTICATION_BACKENDS = (
    'juntagrico.util.auth.AuthenticateWithEmail',
    'django.contrib.auth.backends.ModelBackend'
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'impersonate.middleware.ImpersonateMiddleware',
]

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

ROOT_URLCONF = 'mychruutundruebli.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mychruutundruebli.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'NAME': 'mydatabase',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'mydatabaseuser',
        'PASSWORD': '123password%',
        'OPTIONS': {
          'autocommit': True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Zurich'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

#TODO: adapt values

MEMBER_STRING = 'Mitglied'
MEMBERS_STRING = 'Mitglieder'
ASSIGNMENT_STRING = 'Arbeitseinsatz'
ASSIGNMENTS_STRING = 'Arbeitseinsätze'
ORGANISATION_NAME = 'Juntagrico'
ORGANISATION_LONG_NAME = 'Juntagrico the best thing in the world'
ORGANISATION_ADDRESS = {'name':'Juntagrico',
                    'street' : 'Fakestreet',
                    'number' : '123',
                    'zip' : '12456',
                    'city' : 'Springfield',
                    'extra' : ''}
ORGANISATION_BANK_CONNECTION = {'PC' : '01-123-5',
                            'IBAN' : 'CH 00 12345 67890 12345 67890 10',
                            'BIC' : 'BIC12345XX',
                            'NAME' : 'Juntagrico Bank',
                            'ESR' : '01-123-45'}
INFO_EMAIL = 'info@juntagrico.juntagrico'
SERVER_URL = 'www.juntagrico.juntagrico'
ADMINPORTAL_NAME = 'my.juntagrico'
ADMINPORTAL_SERVER_URL = 'my.juntagrico.juntagrico'
BUSINESS_REGULATIONS = '/static/docs/business_regulations.pdf'
BYLAWS = '/static/docs/bylaws.pdf'
MAIL_TEMPLATE = 'mails/email.html'
STYLE_SHEET = '/static/css/personal.css'
FAVICON = '/static/img/favicon.ico'
BOOTSTRAP = '/static/external/bootstrap-3.3.1/css/bootstrap.min.css'
FAQ_DOC = '/static/doc/fac.pdf'
EXTRA_SUB_INFO = '/static/doc/extra_sub_info.pdf'
ACTIVITY_AREA_INFO = '/static/doc/activity_area_info.pdf'
SHARE_PRICE = '250'
CURRENCY = 'CHF'
ASSIGNMENT_UNIT = 'ENTITY'
PROMOTED_JOB_TYPES = []
PROMOTED_JOBS_AMOUNT = 2
DEPOT_LIST_COVER_SHEETS = 'x'
DEPOT_LIST_OVERVIEWS = 'x'
DEPOT_LIST_GENERATION_DAYS = [1,2,3,4,5,6,7]
BILLING = False
BUSINESS_YEAR_START = {'day':1, 'month':1}
BUSINESS_YEAR_CANCELATION_MONTH = 12
DEMO_USER = ''
DEMO_PWD = ''
IMAGES[key] = {'status_100': '/static/img/status_100.png',
            'status_75': '/static/img/status_75.png',
            'status_50': '/static/img/status_50.png',
            'status_25': '/static/img/status_25.png',
            'status_0': '/static/img/status_0.png',
            'single_full': '/static/img/single_full.png',
            'single_empty': '/static/img/single_empty.png',
            'single_core': '/static/img/single_core.png',
            'core': '/static/img/core.png'}
GOOGLE_API_KEY = 'GOOGLE_API_KEY'
EMAILS = {
    'welcome': 'mails/welcome_mail.txt',
    'co_welcome': 'mails/welcome_added_mail.txt',
    'co_added': 'mails/added_mail.txt',
    'password': 'mails/password_reset_mail.txt',
    'j_reminder': 'mails/job_reminder_mail.txt',
    'j_canceled': 'mails/job_canceled_mail.txt',
    'confirm': 'mails/confirm.txt',
    'j_changed': 'mails/job_time_changed_mail.txt',
    'j_signup': 'mails/job_signup_mail.txt',
    'd_changed': 'mails/depot_changed_mail.txt',
    's_created': 'mails/share_created_mail.txt',
    'n_sub': 'mails/new_subscription.txt',
    's_canceled': 'mails/subscription_canceled_mail.txt',
    'm_canceled': 'mails/membership_canceled_mail.txt',
    'b_share': 'mails/bill_share.txt',
    'b_sub': 'mails/bill_sub.txt',
    'b_esub': 'mails/bill_extrasub.txt'
}
BASE_FEE = ''
ORGANISATION_PHONE = ''
DEFAULT_MAILER = 'juntagrico.util.defaultmailer.Mailer'
ENABLE_REGISTRATION = True'
